ugent-library/biblio-backoffice

internal/engine/publication.go

When you've uploaded more than 50 publications from crossref
and wish to "publish all to biblio", the request takes literally forever.
Reason: it expects `next_page` to be false, but that never happens
if you never increment that page argument.

BatchPublishPublications: without page increment this loop takes forever when multipaged

---

internal/controllers/datasets.go
internal/translations/translations.go

"fixes" #190 
Problem still remains when datacite  does not provide the necessary information
for a record to validate (e.g. no `first_name` for an author). In that case, the flash
box is too small, and there are no specific field (e.g. `first_name`) to which we can
attach that error.

Fix issue 190

---

internal/controllers/publications.go
internal/translations/translations.go

one question though: if an identifier is not given, the code from biblio-backend creates an empty publication.
Is that intended?

show errors on publication import from crossref

---

internal/models/publication.go
services/webapp/internal/controllers/publication_lay_summaries.go
services/webapp/internal/routes/register.go
services/webapp/internal/translations/translations.go
services/webapp/templates/publication/_description_content.gohtml
services/webapp/templates/publication/lay_summaries/_created.gohtml
services/webapp/templates/publication/lay_summaries/_deleted.gohtml
services/webapp/templates/publication/lay_summaries/_form.gohtml
services/webapp/templates/publication/lay_summaries/_form_edit.gohtml
services/webapp/templates/publication/lay_summaries/_modal_confirm_removal.gohtml
services/webapp/templates/publication/lay_summaries/_show.gohtml
services/webapp/templates/publication/lay_summaries/_table_body.gohtml
services/webapp/templates/publication/lay_summaries/_updated.gohtml

Fixes #299 
Notes:
* I use the modal as the `hx-target` (like in the file attributes dialog). So in order to close it, I have to send empty data, and send extra data with attribute `hx-swap-oob` to update the list in `lay-summaries-table`
* If I use also flash messages, then the flash errors are shown, but .. the list is added to the modal. Apparently only one element with `hx-swap-oob` is used as such, and the rest is treated as content for the hx target. No multiple elements with hx-swap-oob??
* the `hx-swap-oob` element is here a `tbody`. Although it uses the preselector "innerHTML" to fetch only the innerhtml of the source element, that matters apparently. If you use `div`, then all `<tr>` and `<td>` elements are filtered out. Weird, very weird

add lay summary

---

services/webapp/internal/controllers/publication_files.go

TODO: disable browser caching? Or does `http.ServeFile` already handles `If-Modified-Since` in a decent way?

download file as attachment; escape utf 8 file names

---

etc/es6/publication.json
internal/backends/es6/publication.go

I've created a separate field `faculty` where all values from `department.tree._id` are copied to.
That makes it easier to go from `f[faculty]=LW` to a filter on `department.tree._id` (which
would be another exception to be added to the parseScope code).
Need to reindex.

add facet faculty

---

internal/app/handlers/publicationediting/files.go
internal/app/handlers/publicationediting/handler.go
internal/app/handlers/publicationviewing/show.go
internal/app/routes/register.go
internal/render/form/form.go
internal/translations/translations.go
templates/form/default/publication/checkbox_no_license.gohtml
templates/publication/confirm_delete_file.gohtml
templates/publication/edit_file.gohtml
templates/publication/files_body.gohtml
templates/publication/refresh_edit_file.gohtml
templates/publication/refresh_files.gohtml
templates/publication/show_files.gohtml
templates/publication/switch_edit_file_by_license.gohtml

TODO:
- edit file modal is not copied from the previous version. That would require the possibility to fetch certain fields from the form element and only render those at the right place in the (custom) template. Now one cannot select those, neither can one distinguish form elements from display elements.
- the "switch by license" is not enabled as it was unclear what the current rules are. The controller is there, and the input `no_license` is configured to fetch that url, but that controller always returns the same form now. Based on the current data, certain fields should not be added to the form, in contrast to before, when fields were simply hidden.
- thumbnail urls are now added before saving (instead of after, which did not save the ThumbnailUrl in the database!)
- flash messages …

Handlers files

---

go.mod
go.sum
internal/app/handlers/publicationcreating/import.go
internal/backends/bibtex/decoder.go

fixes #381 
Fixed:
- skips utf8 bom while reading (bibtex decoder only)
- lowercase bibtex fields before using them. That file had fields like "Author" instead of "author" for which we check in a map!
- resets file pointer (for all decoders, I needed the multipart file to do this); no idea why this doesn't work without, but it is necessary.
- fixes typo in handling template
TODO:
- `Author-Email` contains invalid values within square brackes, i.e. `@`. Should be reported?

fix issue 381

---

internal/app/displays/book_details.go
internal/app/displays/conference_details.go
internal/app/displays/dissertation_details.go
internal/app/displays/editor_details.go
internal/app/handlers/publicationediting/book_details_form.go
internal/app/handlers/publicationediting/book_editor_details_form.go
internal/app/handlers/publicationediting/conference_details_form.go
internal/app/handlers/publicationediting/dissertation_details_form.go

Fixes #479 and more:
* book:
* add missing fields `series_title`, `volume` and `edition`
* conference:
* move `series_title` to top of section
* add missing fields `article_number` and `issue_title`
* rename label for `publication_abbreviation` (was "short journal title", but should be general "publication short title", like in librecat)
* dissertation
* move `series_title` to top of section
* book_editor:
* remove field `publication_abbreviation` which is not in librecat

add missing fields; delete some fields

---

internal/backends/es6/facet_config.go
internal/translations/translations.go
views/dataset/pages/search.gohtml
views/publication/pages/add_multiple_description.gohtml
views/publication/pages/search.gohtml
views/search/_extern_facet.gohtml
views/search/_faculty_facet.gohtml
views/search/_locked_facet.gohtml
views/search/_status_facet.gohtml

* fixes #522 
* fixes incorrect label `for` (and associated checkbox inputs). Were al set to `filter-type- {{.Value}}`. Probably due to my copy-and-pasting. Noticed when adding the "locked" filter which started to interfere with "extern" because of same "id" attributes "filter-type-true" en "filter-type-false".

Fix issue 522

---

internal/backends/es6/dataset.go
internal/backends/es6/publication.go

Current code adds `query.should` with searches on fields all, title and author.full_name as boosts,
even if the user query is empty.

do not add query.should when user query is empty

---

views/publication/pages/add.gohtml

Fixes https://github.com/ugent-library/biblio-backend/issues/341
- I added a recommended option
- Removed columns: I got some feedback about the hierarchy about the options, which would be solved by putting all the options on their own line.

Add copy and html structure for pub import guidance

---

views/dataset/add_department.gohtml
views/dataset/add_project.gohtml
views/dataset/add_publication.gohtml
views/dataset/edit_details.gohtml
views/publication/add_dataset.gohtml
views/publication/add_department.gohtml
views/publication/add_project.gohtml
views/publication/edit_additional_info.gohtml
views/publication/edit_conference.gohtml
views/publication/edit_details.gohtml

This will fix https://github.com/ugent-library/biblio-backend/issues/470 partially:
- The modals will now be wide even when your browser window is smaller.
- It also enhances the focus mode.
- Did not happen for small edit screens such as "librarian tags" (now called reviewer tags), because they don't need to be wide.
_Note: It's still not ideal because the form elements behave strange on smaller screens (the labels and inputs are not wide enough and balanced wrong), but that will be taken up in https://github.com/ugent-library/biblio-backend/issues/498_

Widen modal dialogues for big edit forms

---

internal/app/handlers/datasetsearching/handler.go
internal/app/handlers/publicationsearching/handler.go
internal/backends/es6/dataset.go
internal/backends/es6/facet_config.go
internal/backends/es6/filters.go
internal/backends/es6/publication.go
internal/models/facet.go
internal/models/search_args.go
internal/vocabularies/map.go
views/search/_created_since_facet.gohtml
views/search/_updated_since_facet.gohtml

Fixes #530 and #531
Notes:
* I added a method `SearchArgs#Cleanup` that removes empty slices, or empty values from the filters. Reason: this type of filter introduces empty values in the url as it is a simple text input, while the other filters work with checkboxes that do not send anything when unchecked. The cleanup is called in both handlers of publications and datasets.
* This is a "new" kind of filter, for which no facets are needed
* Since where are filtering here not just on regular values, but on dates, query syntax errors may occur. As I did not see a way to report this errors, I "fixed" it for now by searching for a date in the far future so it always returns zero results. See `es6.ParseTimeSince`. Maybe not ideal, but expected.

filter on dates since for date_created and date_updated

---

views/display/default/list.gohtml
views/display/default/text.gohtml
views/fields/default/text.gohtml
views/form/default/dataset/access_level.gohtml
views/form/default/date.gohtml
views/form/default/radio_button_group.gohtml
views/form/default/select.gohtml
views/form/default/select_repeat.gohtml
views/form/default/text.gohtml
views/form/default/text_area.gohtml
views/form/default/text_repeat.gohtml

This will normally fix https://github.com/ugent-library/biblio-backend/issues/498
_Note: I cannot test this locally. To see if it works, open a publication or dataset, and edit the publication details. The labels should be aligned to the right, and if you make the [screen smaller](https://github.com/ugent-library/biblio-backend/issues/364) they will be balanced below each other._

Align form labels to the right on edit mode

---

internal/backends/interfaces.go
internal/backends/repository/repository.go
internal/commands/dataset.go
internal/commands/publication.go

Fixes #703 
by introducing separate methods `ImportPublication` and `ImportDataset` that requires preexisting timestamps.

Import no update timestamp

---

internal/models/publication.go
views/publication/summary.layout.gohtml

fixes #877 and #876
* renamed `Publication#Reference` to `Publication#SummaryParts` and return array of strings instead of single string, so that we can put the different parts in separate html elements

fix issue 877

---

internal/backends/es6/client.go
internal/backends/es6/dataset.go
internal/backends/es6/dataset_searcher.go
internal/backends/es6/publication.go
internal/backends/es6/publication_searcher.go

Done:
* Added method `searchWithOpts` to `es6.Client` that accepts list of options and the destination response body object in which to decode the response from elasticsearch (may be map or struct reference). This removes the need to read the elasticsearch body in methods decodePublicationRes and decodeDatasetRes. It returns an error, and translates any underlying elasticsearch as an error, instead of doing the same in decodePublicationRes and decodeDatasetRes
* made changes were referred to

simply es6 calls

---

internal/app/handlers/frontoffice/handler.go

cf. https://github.ugent.be/Universiteitsbibliotheek/biblio/pull/57
not urgent: as biblio accepts both time formats in that specific PR

force use of milliseconds in output format

---

internal/translations/translations.go

fixes #937 
simply swaps labels ("extern" has the opposite meaning from "ugent"),
so that explains the bug

swap label for field extern

---

internal/app/displays/book_chapter_details.go
internal/app/displays/book_details.go
internal/app/displays/conference_details.go
internal/app/displays/dataset_details.go
internal/app/displays/dissertation_details.go
internal/app/displays/editor_details.go
internal/app/displays/issue_editor_details.go
internal/app/displays/journal_article_details.go
internal/app/displays/miscellaneous_details.go
internal/app/displays/publication_additional_info.go
internal/app/displays/publication_conference.go
internal/app/displays/publication_details.go
internal/app/handlers/datasetcreating/import.go
internal/app/handlers/datasetediting/details.go
internal/app/handlers/datasetviewing/show.go
internal/app/handlers/publicationcreating/import.go
internal/app/handlers/publicationediting/additional_info.go
internal/app/handlers/publicationediting/conference.go
internal/app/handlers/publicationediting/details.go
internal/app/handlers/publicationviewing/show.go
views/format/boolean_string.gohtml

fixes #948 
done:
* in order to allow for conditionals in the display fields, I had to add the User to every display form (also where it was not used), just like it is done for edit forms.
* show field "legacy" in the display field, when the user is a curator
* use icon circle to display boolean values
* change display field "extern" to use these icons too

add user to view display forms to allow for conditionals; apply for legacy; format boolean

---

internal/app/handlers/frontoffice/handler.go

Two changes happened for issue #975:
- Made sure that what appears in biblio front-office aligns with what people expect to read (not always what the researcher selects)
This is based on the assumption that what appears in the front-office and oai mods is the same -> apparently what appears in the front-office is also what appears in https://biblio.ugent.be/oai ([example](https://biblio.ugent.be/oai?verb=GetRecord&identifier=8694914&metadataPrefix=mods_36))
- Made sure "LicenseNotListed" (other license) records are no longer ignored for datasets. The only things that should be ignored for datasets are "CopyrightUnknown" and "InCopyright". This could also be related to the fact that [some records are not included in FRIS](https://github.com/ugent-library/biblio-backoffice/issues/966#issueco …

Fix front office and oai licenses to make sure GISMO and FRIS receive the correct information

---

views/publication/_files_body.gohtml

Important: when you test this locally you possible won't see the difference between `.DateCreated` and `.DateCreated.Local`

fix issue #935

---

internal/app/handlers/frontoffice/handler.go
internal/app/routes/register.go

fixes #1081 
Done:
* route `/download/:id/:file_id` now supports `HEAD` requests
* route `/download/:id/:file_id` now adds more headers like `Content-Type`, `Content-Type`, `Last-Modified` en `ETag`
* route `/download/:id/:file_id` now supports conditional requests (returning a 304 response)
@phochste

frontoffice download file: add more headers for 304 and head requests

---

views/dataset/_contributors_columns.gohtml
views/publication/_contributors_columns.gohtml

Note: This is a blind PR, it is supposed to look like this:
Visible changes:
- Colour of badge (gray for external, blue for internal)
- Icon for badge (person icon for external, UGent for internal)
- Colour of orcid badge
- Colour of UGent icon
- Turn department into label
Please inform if it does not function as expected.

Make UGent authors stand out more and prepare layout for future

---

internal/app/handlers/frontoffice/handler.go

frontoffice mapping for dataset sets affiliation tree incorrectly.
Copied right code from publication to dataset.
Example: https://backoffice.biblio.ugent.be/frontoffice/dataset/8591831 which show in affiliation tree WE11 - WE - UGent - WE11.

frontoffice handler for dataset: affiliation tree incorrectly adds dep.ID twice (so always in front and at end)

---

internal/app/handlers/base.go
internal/app/routes/register.go
views/dataset/search_hit.gohtml
views/layouts/default.layout.gohtml
views/pages/home.gohtml
views/publication/search_hit.gohtml

* adds map `Constants` to the request context. Now only contains `frontend-url`
* fixes #1152: replaces hard coded value `https://biblio.ugent.be` in the views by `{{index .Constants "frontend-url"}}`
Note: I could not replace the frontend-url [here](https://github.com/ugent-library/biblio-backoffice/blob/dev/internal/app/handlers/orcid/handler.go#L228)

add Constants to request context; fix issue 1152

---

internal/backends/pubmed/client.go

Fixes #1153 , and adds other attributes from pubmed api, using the more rich api:
* add abstract. Language is always set to `eng`. ok?
* uses array `authorList.author` which holds an array of objects, instead of trying to parse `authorString`. Advantage is that `firstName` and `lastName` can now be extracted in full, while previously it showed `<first-name> <abbreviation-of-last-name`. e.g. `Gonzalez N`
* retrieve full journal title instead of abbreviation (`Plant physiology` instead of `Plant Physiol`)
* add language (different from language of abstract?)

use pubmed search arg resulType=core and use richer attributes

---

internal/backends/crossref/client.go

Fixes #1160 
I kept the old code as a fallback, in case fields `isbn-type` and `issn-type`
are not always present.

issue 1160: fix incorrect mapping of (e)issn and (e)isbn in doi import from crossref

---

etc/es6/dataset.json
etc/es6/publication.json
internal/backends/es6/indexed_publication.go

Hotfix
Fixes regression as introduced by https://github.com/ugent-library/biblio-backoffice/commit/489bccecad6c183cb5022ecea60404ff02d9dc63
Requires reindexation

hotfix: copy faculty_id to field all

---

views/search/_has_files_facet.gohtml

on backoffice.bibliodev.ugent.be, the facet "files" does no longer open on click.
It appears that the data-toggle="dropdown" should be data-bs-toggle="dropdown" now,
a change that was no applied here.

data-toggle="dropdown" should be data-bs-toggle="dropdown" now

---

backends/authority/person.go
frontoffice/record.go

In order to deprecate the [catmandu fix in biblio](https://github.ugent.be/Universiteitsbibliotheek/biblio/blob/master/lib/Catmandu/Fix/add_person_data.pm) I added the following to the frontoffice record:
To struct `frontoffice.Person`:
* field `biblio_id` (which has same value as `id`)
* field `name_last_first`
To struct `frontoffice.Record`:
* field `first_author`
* field `last_author`
* field `sole_author`
* field `author_sort`
Field `created_by` is now also filled with all person data needed.
I also changed something in the mapping from the mongodb authority record of a person:
* when a person has no `ugent_department_id`, but `object_class` contains `ugentFormerEmployee`, then affiliation `UGent` is added
* when `object_class` contains `uzEmployee`, then affiliation `UZGent` is …

add missing enrichment for person data in frontoffice record

---

handlers/datasetsearching/search.go
handlers/publicationsearching/search.go

fixes #1299 by truncating requested `page` to last available page (note: only when there are results available). Other out of range requests like a negative number may result in a http status 500 request.

fix issue 1299: cap page to last page when out of range

---

views/layouts/default.layout.gohtml

Context: This needs to be merged in dev later, where the strange behaviour still needs to be fixed in a different file.
Not sure if this is the correct way to do it (e.g. should I define user as well), could not find how it was done before. It does show the correct behaviour:

Make sure sidebar switches colours again like before

---

cli/backends.go
mutate/publication.go

fixes #1310 
note:
* only internal values `private`, `public` and `returned` are used.
* internal store validates the record, so one cannot just a record to public without an ugent author for example

fix issue 1310: add batch method `status.set`

---

handlers/datasetediting/publish.go
handlers/datasetediting/republish.go
handlers/datasetediting/withdraw.go
handlers/publicationcreating/import.go
handlers/publicationediting/republish.go
handlers/publicationediting/withdraw.go
models/person.go
views/dataset/pages/show.gohtml
views/publication/pages/show.gohtml

Should fix https://github.com/ugent-library/biblio-backoffice/issues/851
Shows withdraw button for librarians even when locked
- "view as" does not work locally; so not sure if this works as expected for researchers. The withdrawn button should _not_ show up for researchers when the publication or dataset is locked.
- Nested it in a dumb way and could use some more simple if-else love, but got stuck along the way. Any tips?

Always show withdraw button for librarians

---

cli/update_oai.go
frontoffice/record.go

* `update-oai` command misses `AddItem` call due to which we missed records
* `update-oai` only uses deleted records as `pdeleted`, and therefore we miss records with status `returned`. That being said, this is also the case for the frontoffice code, where we do the same (pdeleted -> `status == "deleted" && has_been_public == true`). Should be derived as follows: `has_been_public == true && status != "public"`. This way we also fix the records in the current frontoffice oai

pdeleted misses "returned"; fix missing pdeleted for frontoffice too

---

frontoffice/record.go
identifiers/ega.go
identifiers/identifier.go
locales/en/default.po
vocabularies/map.go

fixes #1360 
Adds EGA identifier type
Notes:
* what is the `Validate` for if we never use it? e.g. an EGA identifier is probably only starting with EGA, not?
* does the `frontoffice.mapDataset` mapping require changes? I see that only DOI is taken out of the list of identifiers: https://github.com/ugent-library/biblio-backoffice/blob/main/frontoffice/record.go#L910. A change to this would however change all datasets (which is not much luckily).

fix issue 1360

---

go.mod
go.sum
urls/funcmap.go
views/dataset/_message_body.gohtml
views/dataset/search_hit.gohtml
views/publication/_message_body.gohtml
views/publication/search_hit.gohtml

fixes #1375 
how:
* added new func `renderMsg` to template funcmap that receives (unsafe) string and returns html safe string (template.HTML). Implemented as a filter.
* `renderMsg` does the following:
* html escape input
* replace newlines by `<br>`
* replace all https links by `<a>`. Extracting urls was not trivial, as in all of the examples, the urls where hardly ever put between spaces, but mostly between parenthesises, before a dot, after a colon.. So I could not use something like "what is parseable as an url", as that required word extraction first. The limitation on https is due to the library that either allows for matching on a whole set of [schemes](https://pkg.go.dev/mvdan.cc/xurls/v2#Strict) (from http to file, which to much), or either one …

fix issue 1375

---

cypress/e2e/issues/issue-1370.cy.ts
views/shared/_created_by.gohtml
views/shared/_updated_by.gohtml

Date/time format was incorrect [in #1370](https://github.com/ugent-library/biblio-backoffice/issues/1370#issuecomment-2003876362) (and thus in the PR #1394). This PR fixes that.

Feature: informative timestamps update #1370

---

backends/es6/dataset_index.go
backends/es6/publication_index.go

fixes #872 
* Add extra subquery with `DatasetIndex#Search` to fetch all valid facet values that have a document for the current scope, and add those values to the `include` attribute of the requested facet
* Add extra subquery with `PublicationIndex#Search` to fetch all valid facet values that have a document for the current scope, and add those values to the `include` attribute of the requested facet
Problems:
* retrieving of scoped facet values is also done by the dashboard to fetch all valid years. And that code happens to use the Search methods, where that happens all over again.
* this PR makes the page again slower. Haven't find a way to circumvent that.

fix issue 872

---

api/v2/service.go
handlers/frontoffice/handler.go
people/index.go
people/models.go
people/organizations_index_settings.json
people/people_index_settings.json
projects/index.go
projects/projects_index_settings.json

Done:
* make person suggest work (one lettered input returned nothing)
* make organization suggest work (one lettered input returned nothing)
* make project suggest work (one lettered input returned nothing)
* `/frontoffice/person/list` incorrectly returns 404 when one provided id is not found. ID's that are not found should be removed from the list? The frontend converts the result into a map anyway to display facets, and what it does not have, is not used. Before some person/organization pages with publication lists crashed before this.
* filter `sortName` on certain characters, and lower case

Improve biblio issue 1380

---

handlers/mediatypes/handler.go
routes/register.go

The removal of the Wrap method and conversion from gohtml to templ was already done by @verheyenkoen in 7f34da08217bbc5f48194f0bc6a14268a5ad8b87
I now replaced the wrapped handler functionality by the new setup

further remove wrapped handler functionality from mediatypes handler

---

cli/config.go
cli/update_candidate_records_cmd.go
recordsources/plato/source.go
recordsources/source.go
repositories/candidate_records.go

* Store candidate record store connection settings in .env / config.
* Fixes skip duplicate candidate records check.
* Checks for API endpoint http 4xx & 5xx errors

Plato basic auth

---

views/pagination.templ
views/pagination_templ.go
views/urls.go
views/urls_test.go

Roughly related to #1402 
Currently only implemented these methods:
- Adapting methods:
- `.WithPath(path ...string)`
- `.AddQuery(key string, value string)`
- `.WithQuery(query any)` ([see review](https://github.com/ugent-library/biblio-backoffice/pull/1476#discussion_r1585938615))
- `.ClearQuery()`
- Build methods: 
- `.URL() *url.URL`
- `.String() string`
- `.SafeURL() templ.SafeURL`
We can add more when we have use cases for them.

Added URLBuilder for constructing outgoing url's

---

views/dataset/search.templ
views/dataset/search_templ.go
views/publication/search.templ
views/publication/search_templ.go

This
will look like this again
If this obstructs anything anyone is working on, don't worry – I can redo the fix later.

Fix broken lines and dividers for research view

---

views/dataset/search.templ
views/dataset/search_templ.go

What it fixes: in a previous commit I added localization prefixes `reviewer_tags` when configuring the facet `reviewer_tags`. So if you have tags like `mytag` they now appear as `reviewer_tags.mytag`. This bug only appears in the route `/dataset`.

do not translate values of facet reviewer_tags

---

routes/register.go

This sets the navigation for publications and datasets more globally.
Now only on detail pages as other routes require more reorganisation.

set nav for datasets and publications more globally

---

cypress/e2e/issues/issue-1237.cy.ts
cypress/e2e/issues/issue-1241.cy.ts
cypress/e2e/issues/issue-1247.cy.ts
cypress/e2e/issues/issue-1402.cy.ts
cypress/e2e/routing.cy.ts
cypress/support/commands/set-up-dataset.ts
locales/en/default.po
models/dataset.go
views/dataset/details.templ
views/dataset/details_templ.go
views/dataset/edit_details.templ
views/dataset/edit_details_templ.go

In the current dev branch, if you create a dataset **manually**, the fields identifier_type and identifier are missing
in the description (both show/edit).
Reason for this is the if-statement to get identifier and identifier_type out of the map [Identifiers](https://github.com/ugent-library/biblio-backoffice/blob/dev/models/dataset.go#L54):
* https://github.com/ugent-library/biblio-backoffice/blob/dev/views/dataset/details.templ#L68
* https://github.com/ugent-library/biblio-backoffice/blob/dev/views/dataset/edit_details.templ#L67
(P.S. there is no other way to assign variables in templ)
I replaced the `identifierType != ""` by `true` which is always true.
Not sure if we should keep storing the identifier like this
@verheyenkoen detected this

dataset view (show/edit) did not show identifier(type) when manually created

---

views/dataset/show.templ
views/dataset/show_templ.go

@verheyenkoen remarked that the current templ refactor of `datasetediting.Lock` and `datasetediting.Unlock` redirects the user to the dataset search page, instead of back to the dataset detail page (where that button is located).

Refactor to templ: lock/unlock should redirect to dataset detail page, not dataset search page

---

backends/excel/base_exporter.go

fixes #1583 
Apparently, in order to show text as text in Excel, you need to set the "number format" to "@",
which in excelize is equal to setting numfmt to 49.

excel export: format text as regular text

---

views/dataset/projects.templ
views/dataset/projects_templ.go
views/publication/projects.templ
views/publication/projects_templ.go

Editing a dataset was broken when an attached project was not linked to an EUProject. Only found out now since my projects test data changed.
If the bug is already in production, this needs to be patched asap.

Nil reference bugfix in dataset project list when EUProject is nil

---

backends/bibtex/decoder.go

Refs #1626 
The Bibtex `Language` field does not contain a standardized language code (e.g. ISO-369 or BCP47 code): it contains the human name / label of the language (e.g. English, Flemish, Dutch, French,...). This is problematic because of potential ambiguity.
This commit contains a manually made mapping between those labels to the ISO-396-2 code based on: (a) this table published by Library of Congress (https://www.loc.gov/standards/iso639-2/php/code_list.php) and (b) the ISO-369-2 language codes we use in the application.
Moreover, the WOS list isn't exhaustive. They may decide to add new languages without updating the documentation (https://images.webofknowledge.com/images/help/WOS/hs_language.html). e.g. "Romansch" isn't included, but I found records with that language in WOS. It's …

Fixes #1626: adds language support when importing Bibtex records.

---

handlers/candidaterecords/candidate_records.go
views/candidaterecord/confirm_hide.templ
views/candidaterecord/confirm_hide_templ.go
views/candidaterecord/preview.templ
views/candidaterecord/preview_templ.go
views/candidaterecord/summary.templ
views/candidaterecord/summary_templ.go

FIXES #1728
- **Makes sure "rejecting" is now communicated as "rejected as a duplicate"**.
We will add other rejection reasons in the future for other sources, for Plato there will be little other reasons.
Restoring remains possible for all parties.
- **Make sure "View" is hidden for researchers for now.**
Researchers were able to delete a publication after import, which breaks the link. This has caused confusion with our proxy testers.
This is now hidden for researchers and proxies, but we kept it for workflow purposes for reviewers.

Restrict restore of rejected suggestions by biblio team members #1728
