ugent-library/biblio-backoffice

templates/publication/files/_edit.gohtml

do not put form element within modal layout

---

internal/controllers/datasets.go
internal/controllers/publications.go
internal/models/dataset.go
internal/models/publication.go
templates/dataset/_hit.gohtml
templates/dataset/_summary_body.gohtml
templates/dataset/publications/_show.gohtml
templates/publication/_hit.gohtml
templates/publication/_summary_body.gohtml
templates/publication/datasets/_show.gohtml

show related_dataset_count and related_publication_count on listing pages

---

templates/publication/add_multiple.gohtml

fixes #141 Not sure about the label

add wos import instructions

---

templates/dataset/add.gohtml

fixes #153 (sorry wrong number in branch name)

change link to instruction page on adding datasets

---

internal/translations/translations.go
templates/search/_status_facet.gohtml

translate facet status

---

templates/publication/add_multiple_confirm.gohtml

fix issue #156

---

templates/dataset/add_publish.gohtml
templates/publication/add_single_publish.gohtml

change congratulation text when publication/dataset is published

---

templates/publication/additional_info/_edit.gohtml
templates/publication/additional_info/_show.gohtml
templates/publication/details/edit/_book.gohtml
templates/publication/details/edit/_book_chapter.gohtml
templates/publication/details/edit/_book_editor.gohtml
templates/publication/details/edit/_conference.gohtml
templates/publication/details/edit/_dissertation.gohtml
templates/publication/details/edit/_issue_editor.gohtml
templates/publication/details/edit/_journal_article.gohtml
templates/publication/details/edit/_miscellaneous.gohtml
templates/publication/details/show/_book.gohtml
templates/publication/details/show/_book_chapter.gohtml
templates/publication/details/show/_book_editor.gohtml
templates/publication/details/show/_conference.gohtml
templates/publication/details/show/_dissertation.gohtml
templates/publication/details/show/_issue_editor.gohtml
templates/publication/details/show/_journal_article.gohtml
templates/publication/details/show/_miscellaneous.gohtml

fixes #75 
todo: review other data types than journal_article. I had to come up with own rules for these.

Fix issue 75

---

templates/dataset/_hit.gohtml
templates/dataset/_summary_body.gohtml
templates/publication/datasets/_modal_hits.gohtml
templates/publication/datasets/_show.gohtml

fix issue 247: add target _blank to if-external-link

---

internal/translations/translations.go
templates/dataset/details/_edit.gohtml
templates/publication/details/edit/_book.gohtml
templates/publication/details/edit/_book_chapter.gohtml
templates/publication/details/edit/_book_editor.gohtml
templates/publication/details/edit/_conference.gohtml
templates/publication/details/edit/_dissertation.gohtml
templates/publication/details/edit/_issue_editor.gohtml
templates/publication/details/edit/_journal_article.gohtml
templates/publication/details/edit/_miscellaneous.gohtml

Fix issue 230

---

internal/controllers/publication_files.go
templates/publication/files/_edit.gohtml
templates/publication/files/_update.gohtml

See #248 
Without https://github.ugent.be/Universiteitsbibliotheek/librecat/pull/644 will do anything new.

handle form errors in file metadata dialog

---

templates/publication/files/_edit.gohtml

add target blank to external links, and style them

---

services/webapp/templates/dataset/_hit.gohtml
services/webapp/templates/dataset/publications/_modal_hits.gohtml
services/webapp/templates/dataset/publications/_show.gohtml
services/webapp/templates/publication/_hit.gohtml
services/webapp/templates/publication/_summary_body.gohtml
services/webapp/templates/publication/_thumbnail.gohtml
services/webapp/templates/publication/add_multiple_confirm.gohtml
services/webapp/templates/publication/add_multiple_description.gohtml

add link to publication/dataset on thumbnail, when applicable

---

services/webapp/internal/routes/register.go

cf. https://github.com/ugent-library/biblio-backend/issues/289

project id can contain slashes

---

services/webapp/templates/dataset/contributors/_choose.gohtml
services/webapp/templates/dataset/contributors/_columns.gohtml
services/webapp/templates/dataset/contributors/_confirm_remove.gohtml
services/webapp/templates/dataset/contributors/_form.gohtml
services/webapp/templates/dataset/contributors/_table.gohtml

fix issue 306

---

services/webapp/templates/dataset/details/_edit.gohtml
services/webapp/templates/form_builder/_text.gohtml
services/webapp/templates/form_builder/_text_repeat.gohtml
services/webapp/templates/publication/details/edit/_book.gohtml
services/webapp/templates/publication/details/edit/_book_chapter.gohtml
services/webapp/templates/publication/details/edit/_book_editor.gohtml
services/webapp/templates/publication/details/edit/_conference.gohtml
services/webapp/templates/publication/details/edit/_dissertation.gohtml
services/webapp/templates/publication/details/edit/_issue_editor.gohtml
services/webapp/templates/publication/details/edit/_journal_article.gohtml
services/webapp/templates/publication/details/edit/_miscellaneous.gohtml

Fixes #278 
Done:
* Placeholder support for Text and TextRepeat
* publication: added placeholders for external identifiers wos_id, issn, e-issn, isbn, e-isbn, arxiv, pubmed en escid
* publication: added placeholders for defense_date and defense_time
* dataset: added placeholder for other_license (url)

Fix issue 278

---

services/webapp/internal/translations/translations.go
services/webapp/templates/publication/add.gohtml
services/webapp/templates/publication/add_bibtex.gohtml
services/webapp/templates/publication/add_identifier.gohtml
services/webapp/templates/publication/add_wos.gohtml
services/webapp/templates/publication/datasets/_modal.gohtml
services/webapp/templates/publication/datasets/_show.gohtml
services/webapp/templates/publication/files/_edit.gohtml
services/webapp/templates/publication/projects/_modal.gohtml

fix issue 336

---

internal/backends/es6/dataset.go
internal/backends/es6/publication.go
internal/backends/interfaces.go
services/webapp/internal/controllers/dataset_publications.go
services/webapp/internal/controllers/datasets.go
services/webapp/internal/controllers/publication_datasets.go
services/webapp/internal/controllers/publications.go

* make facets optional in DatasetSearchService and PublicationSearchService
* remove exclusion filter when they are empty. They lead to zero results in dataset_publications.go and publication_datasets.go

optional facets; no exclude filters when empty

---

internal/models/contributor.go
internal/models/dataset.go
internal/models/publication.go
internal/models/text.go
internal/validation/util.go
internal/vocabularies/map.go
services/webapp/internal/controllers/publications.go
services/webapp/templates/form_builder/_text_repeat.gohtml

See https://github.com/ugent-library/biblio-backend/issues/382
See https://github.com/ugent-library/biblio-backend/issues/383
P.S. attributes "publication" and "year" are made required (on publish)
due to hints in the gui, while these were not required in LibreCat.

Snapstore validation dataset and publication

---

internal/app/handlers/datasetediting/department.go
internal/app/handlers/datasetediting/handler.go
internal/models/dataset.go
internal/services/webapp/routes/register.go
templates/dataset/add_department.gohtml
templates/dataset/confirm_delete_department.gohtml
templates/dataset/department_suggestions.gohtml
templates/dataset/departments_table.gohtml
templates/dataset/refresh_add_department.gohtml
templates/dataset/refresh_departments.gohtml
templates/dataset/show_departments.gohtml
templates/dataset/show_description.gohtml

Ports dataset/departments to new controller logic.

Handlers dataset departments

---

internal/app/handlers/publicationcreating/import.go

fix issue 458: make pagination links work by redirecting to page itself

---

etc/es6/dataset.json
etc/es6/publication.json

Fixes #491 
This changes the elasticsearch mapping, so reindexing is needed to see the changes in a action

fix typo: use search analyzer phrase_edge_ngram_search instead of phrase_edge_ngram

---

views/search/_faculty_facet.gohtml
views/search/_status_facet.gohtml
views/search/_type_facet.gohtml

add count to facets

---

internal/app/handlers/datasetediting/details.go

fix unwanted closing of dataset modal for now by disabling form

---

internal/backends/es6/facet_config.go
views/publication/pages/add_multiple_description.gohtml
views/publication/pages/search.gohtml
views/search/_publication_status_facet.gohtml

fix issue 520; add missing facet "extern" on page add_multiple_description

---

internal/app/handlers/mediatypes/handler.go
internal/translations/translations.go
views/media_types/suggest.gohtml

fixes #466 
@mietcls I've used the text `Add custom data format` instead of `Add new data format` as that last suggests that you're updating an existing vocabulary.

fix issue 466

---

etc/es6/publication.json
internal/backends/es6/facet_config.go
internal/models/publication.go
internal/vocabularies/map.go
views/search/_vabb_type_facet.gohtml

TODO:
* merge https://github.ugent.be/Universiteitsbibliotheek/librecat/pull/663
* reexport publications from LibreCat
* recreate index for publications
* reimport publications
Fixes #526

Fix issue 526

---

internal/backends/es6/indexed_dataset.go
internal/backends/es6/indexed_publication.go
internal/backends/es6/time.go

format all date as UTC, with millisecond precision

---

views/dataset/pages/search.gohtml
views/publication/pages/search.gohtml

fix issue 544

---

internal/app/handlers/datasetediting/contributors.go
internal/app/handlers/publicationediting/contributors.go

Add missing fields to `Contributor` during import from biblio:
* `FullName` (necessary?)
* `UGentID`
* `Department` (requires an additional lookup to fetch the department name)
* `ORCID`

add other biblio person fields to Contributor during import

---

internal/commands/file.go
internal/models/publication.go
internal/translations/translations.go

fixes #718 but now file size is also checked

Fix issue 718 part 2

---

views/publication/pages/search.gohtml

Corrects the previously merged PR

Put facet parent space limiting class on correct parent element

---

internal/app/handlers/datasetediting/publication.go
internal/app/handlers/publicationediting/dataset.go

fix issue 702

---

internal/app/handlers/frontoffice/embargo.go
internal/app/routes/register.go
internal/backends/interfaces.go
internal/backends/repository/repository.go
internal/models/dataset.go
internal/models/publication.go
internal/snapstore/client.go

add routers to clear embargo for publications and datasets

add router that clears embargo for publications and datasets

---

internal/translations/translations.go
views/dataset/edit_message.gohtml
views/dataset/show_activity.gohtml
views/form/file/embargo_after.gohtml
views/form/file/embargo_end.gohtml
views/form/file/file_access_level.gohtml
views/form/file/license.gohtml
views/form/file/publication_version.gohtml
views/form/file/sections/access_level.gohtml
views/form/file/sections/embargo.gohtml
views/pages/home.gohtml
views/publication/_files_body.gohtml
views/publication/edit_message.gohtml
views/publication/pages/add_identifier.gohtml
views/publication/show_activity.gohtml
views/publication/show_files.gohtml

Add links to research tips, adjust guidance and fix some typos

Research tips copy

---

internal/app/handlers/frontoffice/handler.go
internal/backends/interfaces.go
internal/backends/repository/repository.go
internal/snapstore/client.go

use backend postgres to select publications/datasets in order to avoid pagination limit in elasticsearch

---

internal/app/handlers/frontoffice/handler.go

* added copyright statement for empty licenses
* changed copyright statement for LicenseNotListed
* fixed typo in copyright statement
* added OtherLicense to the model
* always copy OtherLicense from dataset to biblio publication (hidden if empty)
* only copy License from dataset to biblio publication if a real license (e.g. not "LicenseNotListed" or "CopyrightUnknown")

Fix issue 734

---

etc/es6/publication.json

fixes #816 
requires reindexation of publications

add missing copy_to statements for publication

---

internal/commands/publication.go
internal/commands/server.go

Important: command line option `-mode` is no longer in use. A Problem?

move create handle action from pipeline to command

---

views/dataset/search_hit.gohtml

fix issue 831

---

views/dataset/_publications_body.gohtml
views/publication/_datasets_body.gohtml

Fix issue 830

---

etc/es6/publication.json
internal/backends/es6/publication.go

fixes #926 
TODO:
* update mapping in elasticsearch (do we use aliases?)
* reindex publications

Fix issue 926

---

internal/backends/es6/publication.go

issue #926: search also on wos_id

---

internal/backends/excel/dataset/dataset_list_exporter.go

fix typo to fix issue 967

---

views/publication/_files_body.gohtml

fix issue #950

---

views/search/_reviewer_tags_facet.gohtml

fix issue #986

---

internal/backends/authority/person.go
internal/util/util.go

fixes #991 (branch name is wrong)

parse outside weird boolean values

---

internal/backends/excel/publication/publication_list_exporter.go

reviewer xlsx: add missing fields

---

internal/vocabularies/map.go

configure (forgotten) facet has_message

---

internal/backends/excel/dataset/dataset_list_exporter.go
internal/backends/excel/publication/publication_list_exporter.go

construct contributor full name from first- and lastname when needed

---

etc/es6/dataset.json
etc/es6/publication.json
internal/backends/es6/dataset.go
internal/backends/es6/publication.go

fixes #1015
Requires reindexation

fix issue 1015: search on department identifier in global search

---

views/publication/_files_body.gohtml

fix issue #1021

---

internal/backends/repository/repository.go

fix issue 1030: dataset's filtered publications should filter on viewable publications, not deletable

---

views/dataset/_thumbnail.gohtml
views/publication/_thumbnail.gohtml

Make sure thumbnails do not overflow on search page

---

internal/app/handlers/dashboard/publications.go
internal/backends/es6/indexed_publication.go
internal/backends/es6/publication.go
views/dashboard/pages/publications.gohtml

The code works, but parking this for now. I would like a double-check to ensure the results of the dashboard are matching with expected outcomes from the review team.

Issue 601: dashboard: unclassified publications without department or UGent only.

---

internal/app/displays/book_chapter_details.go
internal/app/displays/book_details.go
internal/app/displays/conference_details.go
internal/app/displays/dissertation_details.go
internal/app/displays/editor_details.go
internal/app/displays/issue_editor_details.go
internal/app/displays/journal_article_details.go
internal/app/displays/miscellaneous_details.go
views/format/doi.gohtml
views/format/wos_id.gohtml

Fix issue 973

---

internal/translations/translations.go
internal/vocabularies/map.go

issue 1065: add organization FlandersMake

---

views/dataset/_message_body.gohtml
views/publication/_message_body.gohtml

Fixes Issue #1089 https://github.com/ugent-library/biblio-backoffice/issues/1089

Make sure people can always see the contact details

---

etc/es6/dataset.json
internal/app/displays/dataset_details.go
internal/app/handlers/datasetediting/details.go
internal/app/handlers/frontoffice/handler.go
internal/backends/datacite/client.go
internal/models/dataset.go
internal/translations/translations.go

fixes #1063 
This is a new field in the backend, but not in the frontend:
* reindex all datasets in the backend (easy)
* index datasets only in the frontend (easy).

fix issue 1063: add language tag to model dataset

---

internal/app/handlers/frontoffice/handler.go

fix issue 1115: hide non public related publications/datasets

---

internal/backends/ris/decoder.go

Fixes #1123 
* keywords may cross line boundaries, and the current approach (split by newline first, then by colon) makes unneeded splits. Solved by rejoining full value, and then split by colon.
* fixed incorrect import of long abstracts with newlines. Example see abstract in example #1123. 
* moved split logic from `mapRecord` to `decode` (so tags like CT are also covered)

ris import: fix incorrect splitting of values

---

internal/app/displays/dataset_details.go
internal/app/handlers/datasetediting/details.go
internal/translations/translations.go
views/dataset/_message_body.gohtml
views/dataset/pages/add.gohtml

Copy changes, mail, research tip and sequence changes for datasets

---

views/dataset/pages/add.gohtml
views/dataset/pages/add_identifier.gohtml

Align guidance cards for adding a dataset

---

cypress/e2e/issues/issue-1123.cy.ts
cypress/fixtures/wos-000963572100001.txt

Cypress tests for #1123

---

views/pages/home.gohtml

Remove outdated Biblio warning

---

internal/backends/ris/decoder.go

fix issue 1128: Add language English to abstracts when importing from WoS

---

internal/backends/datacite/client.go

fixes #679 
See issue for full discussion

issue 679: only import descriptions with descriptionType Abstract as abstracts

---

views/publication/_show_lock_message.gohtml
views/publication/show_description.gohtml

fixes #1125 
note that there is also a separate branch `fix_issue_1125` from @verheyenkoen that
contains a (unmerged) cypress test for this.

fix issue 1125

---

views/publication/pages/add.gohtml

Period.
Fixes https://github.com/ugent-library/biblio-backoffice/issues/1053 #1053

Add a missing dot.

---

internal/translations/translations.go
internal/vocabularies/map.go

First non-blind commit, hurrah!
Fixes https://github.com/ugent-library/biblio-backoffice/issues/1176

Remove D2 Student thesis classifications and translations

---

identifiers/identifier.go
internal/vocabularies/map.go
views/dataset/pages/add.gohtml

Rename BioProject to ENA BioProject to avoid confusion

---

views/dashboard/pages/datasets.gohtml
views/dashboard/pages/publications.gohtml

Fixes https://github.com/ugent-library/biblio-backoffice/issues/1187
In the future I'd like to add a question mark in the table instead of this long explanation, but I have not figured out how yet.

Explain why totals are off

---

views/publication/batch/show.gohtml

Completes https://github.com/ugent-library/biblio-backoffice/issues/1148 with documentation.
Branched this one from dev now.

Update documentation about batch commands and link to gitbook

---

internal/app/handlers/datasetcreating/import.go

Let's do the review thing.
fixes #1181

Fixes #1181: DOI import for datasets does not check for doubles any longer

---

views/dataset/pages/search.gohtml
views/pages/home.gohtml
views/publication/pages/search.gohtml

Fixes https://github.com/ugent-library/biblio-backoffice/issues/1208

Add maintenance message on home and overview tabs

---

etc/es6/dataset.json
etc/es6/publication.json
internal/backends/es6/indexed_dataset.go
internal/backends/es6/indexed_publication.go

fix issue 1227

---

views/dataset/_contributors_body.gohtml
views/dataset/_contributors_columns.gohtml
views/publication/_contributors_body.gohtml
views/publication/_contributors_columns.gohtml

Clean up author tables and simplify

---

etc/es6/publication.json
internal/backends/es6/indexed_publication.go

fixes #1227 latest comment about conference name/title not being searchable

fix issue 1227: add conference_name to searchable fields

---

views/dataset/pages/add_description.gohtml
views/dataset/pages/show.gohtml
views/publication/pages/add_multiple_confirm_show.gohtml
views/publication/pages/add_multiple_show.gohtml
views/publication/pages/add_single_description.gohtml
views/publication/pages/show.gohtml

Fixes #1247 
Later: remove unused css from this project and prototype

Remove superfluous collapsible header interfering with dropdowns

---

backends/ecoom/ecoom.go
backends/jcr/jcr.go
cli/update_external_fields_cmd.go
frontoffice/record.go
go.mod
go.sum
repositories/repo.go

* Adds fixer that enriches publication with ecoom data
* Adds fixer that enriches publication with jcr data
* Adds command that runs above fixer on publications with status "public".

Publication update external fields

---

cli/backends.go
mutate/publication.go

fix issue 1311: add batch operation 'lock' and 'unlock'

---

server/dataset.go
server/publication.go

fixes #1223, but now with cleanup instructions for publications and datasets

fix issue 1223: cleanup publications and datasets

---

backends/peopleservice/client.go

remove dependency on model api of peopleservice

---

ctx/ctx.go
go.mod
go.sum
handlers/base.go
routes/register.go
views/layouts/default.layout.gohtml
views/page_layout.templ
views/page_layout_templ.go

fixes #1340 
Note that we allow as image sources the data protocol, as these are referenced throughout our code and in CSS.
See for examples like `data:image/svg+xml`

fix issue 1340: add CSP headers

---

vocabularies/map.go

fix issue 1349: move GUK from socs to faculties

---

backends/mods36/encoder.go
backends/oaidc/encoder.go
cli/update_oai.go

Replaces https://github.com/ugent-library/biblio-backoffice/pull/1353

fix issue 1353

---

cli/server_cmd.go
cypress/e2e/issues/issue-1227.cy.ts
cypress/e2e/issues/issue-1370.cy.ts
cypress/support/util.ts
helpers/funcmap.go
views/dataset/summary.layout.gohtml
views/publication/_files_body.gohtml
views/shared/_created_by.gohtml
views/shared/_updated_by.gohtml

This PR makes created/edited timestamps more informative as described in #1370.

Feature: informative timestamps #1370

---

cypress/e2e/issues/issue-0869.cy.ts
cypress/e2e/issues/issue-1370.cy.ts
views/publication/_files_body.gohtml

Fixed date format for upload date as described in #869.

File uploads: fixed uploaded date format #869

---

views/dataset/pages/search.gohtml
views/publication/pages/search.gohtml
views/user_dashboard.templ
views/user_dashboard_templ.go

For upcoming maintenance. Expected outcome:
User dashboard
Publications overview
Datasets overview

Add status messages for downtime

---

views/dataset/pages/search.gohtml
views/publication/pages/search.gohtml
views/user_dashboard.templ
views/user_dashboard_templ.go

Migration happened successfully.

Remove downtime message

---

backends/datacite/client.go

fix issue 1385

---

handlers/datasetediting/abstract.go
handlers/publicationediting/abstract.go
handlers/publicationediting/lay_summary.go

Fix issue 1420

---

ctx/dataset.go
ctx/publication.go

To be used for future handlers that lack the old Wrap method

add middleware for viewing and editing publications and datasets

---

views/form/default/checkbox.gohtml
views/search/_classification_facet.gohtml
views/search/_completeness_facet.gohtml
views/search/_extern_facet.gohtml
views/search/_faculty_id_facet.gohtml
views/search/_file_relation_facet.gohtml
views/search/_has_files_facet.gohtml
views/search/_has_message_facet.gohtml
views/search/_identifier_type_facet.gohtml
views/search/_legacy_facet.gohtml
views/search/_locked_facet.gohtml
views/search/_publication_status_facet.gohtml
views/search/_reviewer_tags_facet.gohtml
views/search/_status_facet.gohtml
views/search/_type_facet.gohtml
views/search/_vabb_type_facet.gohtml
views/search/_wos_type_facet.gohtml
views/search/_year_facet.gohtml

Enhanced facet filter margins with gap so there's no need to determine the last item and set margin dynamically.
CLOSES #1393

Enhanced facet filter margins

---

views/show_modal_layout.templ
views/show_modal_layout_templ.go

Removes superfluous `<div id="modal">` within already `<div id="modal">`

remove double div id=modal

---

handlers/dashboard/publications.go
localize/localize.go
views/curator_dashboard_publications.templ
views/curator_dashboard_publications_templ.go

fix curator dashboard publication types order

---

recordsources/plato/record.go
views/publication/details.templ
views/publication/details_templ.go
views/publication/preview.templ
views/publication/preview_templ.go

Assorted fixes and improvements during import of plato records per issue #1587 
* Auto-add dutch to abstracts
* Auto-add publication place & publishing status
* Auto-add organizations extracted from supervisor organizations
* Fixes ISSN / ISBN display field in publication detail page

Issue 1587 - Data improvements Plato implementation

---

handlers/publicationbatch/handler.go
repositories/repo.go

fixes #1607 
done:
* makes csv reader allow spaces around csv parts (it broke already there)
* fixes nil pointer dereference
* add error message "publication not found"

fix issue #1607

---

views/dataset/search.templ
views/dataset/search_templ.go
views/publication/search.templ
views/publication/search_templ.go
views/search.templ
views/search_templ.go

Hide "Select all" for librarian tags facet filters

---

backends/authority/project.go

fix issue #1613: Can no longer see project description in search

---

views/form/form.templ
views/form/form_templ.go

fix issue #1612: radio button group do not set values

---

locales/en/default.po
views/dataset/edit_details.templ
views/dataset/edit_details_templ.go
views/dataset/edit_reviewer_tags.templ
views/dataset/edit_reviewer_tags_templ.go
views/publication/edit_additional_info.templ
views/publication/edit_additional_info_templ.go
views/publication/edit_reviewer_tags.templ
views/publication/edit_reviewer_tags_templ.go

fix issue #1620: add help message to field type Tags

---

handlers/dashboard.go
views/drafts_to_complete.templ
views/drafts_to_complete_templ.go

fix issue #1610: add missing filter locked=false in ES filter or url filter

---

CHANGELOG.md
views/publication/activity.templ
views/publication/activity_templ.go

Fix issue #1632 and add changelog starting from June

Fix biblio message links not showing for publications in activity tab

---

handlers/publicationediting/link.go

fix issue #1640: validation skipped when creating new link on publication

---

views/publication/edit_details.templ
views/publication/edit_details_templ.go

Fixed classification label in edit publication details for researchers

---

views/publication/edit_details.templ
views/publication/edit_details_templ.go

Removed empty option for classification field + added required label

---

views/publication/edit_link.templ
views/publication/edit_link_templ.go

fix issue 1643: add form errors also above add/edit link modal

---

backends/ris/decoder.go
cypress/e2e/issues/issue-1625.cy.ts
cypress/fixtures/wos-000500696400004-2.txt
cypress/fixtures/wos-000500696400004.txt

Fix editor (BE/ED) import from WoS files #1625

---

cypress/e2e/datasets/add/import-by-identifier.cy.ts
cypress/e2e/issues/issue-0844.cy.ts
cypress/e2e/issues/issue-0961.cy.ts
cypress/e2e/issues/issue-1124.cy.ts
cypress/e2e/issues/issue-1125.cy.ts
cypress/e2e/issues/issue-1246.cy.ts
cypress/e2e/issues/issue-1247.cy.ts
cypress/e2e/issues/issue-1278.cy.ts
cypress/e2e/login.cy.ts
cypress/e2e/publications/add/import-by-identifier.cy.ts
cypress/e2e/publications/batch.cy.ts
handlers/authenticating/handler.go
handlers/errors.go

Also adapted curator login behaviour: curators are now always logged on in librarian mode but can still switch to researcher mode.
FIXES #1390

Cleared curator role cookie on logout

---

views/contributor/contributor_suggest_form.templ
views/contributor/contributor_suggest_form_templ.go

Converted contributor suggest search fields to type=search #1691

---

backends/authority/common.go
backends/authority/person.go
ctx/ctx.go
handlers/proxies/proxies.go
models/person.go
repositories/permissions.go
repositories/proxies.go
views/page_layout.templ

fix permissions and proxy methods when a person has multiple ids

---

views/dataset/publications.templ
views/dataset/publications_templ.go
views/publication/datasets.templ
views/publication/datasets_templ.go

Fix display of related items

---

views/candidaterecord/list.templ
views/candidaterecord/list_templ.go
views/dashboard/candidate_records.templ
views/dashboard/candidate_records_templ.go

Add candidate records info to dashboard page #1722

---

cypress/e2e/issues/issue-1718.cy.ts
views/proxy/add.templ
views/proxy/add_templ.go
views/proxy/edit.templ
views/proxy/edit_templ.go
views/proxy/index.templ
views/proxy/index_templ.go
views/proxy/people_suggestions.templ
views/proxy/people_suggestions_templ.go
views/proxy/user_list.templ
views/proxy/user_list_templ.go

Proxy researcher search fix #1718

---

repositories/candidate_records.go
views/candidaterecord/summary.templ
views/candidaterecord/summary_templ.go

Extend candidate records expiration date

---

ctx/ctx.go

To be tested and deployed:
Show Plato suggestions to everyone.

Show Plato for all faculties
